(0, 0) 700
(0, 1) 949
(0, 2) 943
(0, 3) 806
(1, 0) 723
(1, 1) 818
(1, 2) 858
(1, 3) 769
(2, 0) 852
(2, 1) 815
(2, 2) 792
(2, 3) 705
(0, 0) 811
(0, 1) 886
(0, 2) 836
(0, 3) 654
(1, 0) 740
(1, 1) 868
(1, 2) 813
(1, 3) 668
(2, 0) 736
(2, 1) 896
(2, 2) 933
(2, 3) 889
(0, 0) 769
(0, 1) 924
(0, 2) 948
(0, 3) 705
(1, 0) 759
(1, 1) 849
(1, 2) 832
(1, 3) 723
(2, 0) 678
(2, 1) 839
(2, 2) 817
(2, 3) 887
EM
0.0
0.0
0.0
0.0
0.0
6.47921760391198
5.944055944055944
0.0
0.0
0.0
0.0
0.0
EN
0.0
2.423603793466807
9.862142099681867
0.0
0.0
3.4229828850855744
5.128205128205128
0.0
0.0
7.975460122699387
5.42929292929293
0.0
EM
0.0
0.0
0.0
0.0
0.0
6.105990783410138
6.273062730627306
0.0
0.0
0.0
0.0
0.0
MN
55.980271270036994
0.2257336343115124
0.0
0.0
9.054054054054054
68.89400921658986
67.03567035670358
13.323353293413174
0.0
0.0
0.4287245444801715
63.44206974128234
EN
0.0
2.4891774891774894
9.81012658227848
0.0
0.0
3.297997644287397
5.288461538461538
0.0
0.0
7.747318235995232
5.263157894736842
0.0
MN
59.03771131339401
0.21645021645021645
0.0
0.0
8.827404479578393
70.43580683156655
65.5048076923077
12.309820193637622
0.0
0.0
0.4895960832313341
63.58511837655016
Traceback (most recent call last):
  File "som_random_init.py", line 380, in <module>
    plot_som('h500', composites_ERA5, 'ERA5')
  File "som_random_init.py", line 115, in plot_som
    index = var_list.index(var)
ValueError: 'h500' is not in list
